name: Deno Deploy
run-name: "Deploy ${{ inputs.app-name }}"

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: "Name of the app to deploy"
        required: true

jobs:
  deploy:
    name: Deploy ${{ inputs.app-name }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ${{inputs.app-name}} # the name of the project on Deno Deploy
          entrypoint: apps/${{inputs.app-name}}/src/main.ts # the entrypoint to deploy
          import-map: import_map.json